services:

  db:
    image: postgres:16-alpine
    container_name: gamificacao-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gamificacaodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: gamificacao-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    build: .
    container_name: gamificacao-app
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: gamificacaodb
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: